# Generated by Django 5.2.17 on 2026-09-13 22:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('CONTA', 'Criação e manutenção da conta')], max_length=20, verbose_name='finalidade')),
                ('policy_version', models.CharField(max_length=10, verbose_name='versao da politica')),
                ('granted_at', models.DateTimeField(auto_now_add=True, verbose_name='aceito em')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revogado em')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consent_records', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de consentimento',
                'verbose_name_plural': 'registros de consentimento',
                'ordering': ['-granted_at'],
                'indexes': [models.Index(fields=['user', 'purpose', 'policy_version', 'revoked_at'], name='privacy_con_user_id_2d224e_idx')],
            },
        ),
    ]
