# Generated by Django 5.2.17 on 2026-09-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consentrecord',
            name='purpose',
            field=models.CharField(choices=[('CONTA', 'Criação e manutenção da conta'), ('MATERIAL_SALVO', 'Guardar materiais na conta')], max_length=20, verbose_name='finalidade'),
        ),
    ]
