# Generated by Django 5.2.17 on 2026-09-06 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='hash do token')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='usado em')),
                ('invalidated_at', models.DateTimeField(blank=True, null=True, verbose_name='invalidado em')),
                ('requested_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereco da solicitacao')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='password_reset_tokens', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'token de recuperacao de senha',
                'verbose_name_plural': 'tokens de recuperacao de senha',
                'ordering': ['-created_at'],
            },
        ),
    ]
