# Generated by Django 5.2.17 on 2026-09-13 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
        ('otp_totp', '0003_add_timestamps'),
    ]

    operations = [
        migrations.CreateModel(
            name='EncryptedTOTPDevice',
            fields=[
            ],
            options={
                'verbose_name': 'dispositivo 2FA cifrado',
                'verbose_name_plural': 'dispositivos 2FA cifrados',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('otp_totp.totpdevice',),
        ),
    ]
