"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import base64
import binascii
import os
import sys
from datetime import timedelta
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get("DJANGO_DEBUG", "0") == "1"

# SECURITY WARNING: keep the secret key used in production secret!
# A chave que assina cookies, tokens de CSRF e mensagens vem só do ambiente
# (requisito 3.6). Em produção a ausência dela derruba a inicialização: cair
# silenciosamente num valor fixo, escrito aqui no código e visível no GitHub,
# daria a qualquer pessoa a chave de assinatura do sistema publicado.
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "")
if not SECRET_KEY:
    if not DEBUG and "test" not in sys.argv:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY nao definida no ambiente.")
    SECRET_KEY = "minha chave gerada para desenvolvimento"

# Endereços que a aplicação aceita atender, separados por vírgula na variável
# de ambiente. Publicar em outro domínio passa a ser mudança de configuração no
# painel do Render, e não alteração de código. O padrão cobre o uso local.
ALLOWED_HOSTS = [
    host.strip()
    for host in os.environ.get("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
    if host.strip()
]

# O Render informa o endereço público do serviço nesta variável. Fica como rede
# de segurança: se alguém esquecer de preencher ALLOWED_HOSTS no painel, o
# serviço ainda responde no próprio endereço em vez de recusar toda requisição.
RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME and RENDER_EXTERNAL_HOSTNAME not in ALLOWED_HOSTS:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Origens aceitas em requisições que alteram dados, montadas a partir dos
# mesmos hosts. O Django exige o esquema junto do endereço, e em produção o
# acesso é sempre por https. Um host com "*" não vira origem: curinga não é
# aceito aqui, e incluí-lo derrubaria a aplicação na inicialização.
CSRF_TRUSTED_ORIGINS = [f"https://{host}" for host in ALLOWED_HOSTS if "*" not in host]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    # Bibliotecas de terceiros
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "axes",

    # Aplicativos do projeto
    "apps.accounts",
    "apps.catalog",
    "apps.privacy",
    "apps.audit",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django_otp.middleware.OTPMiddleware",
    # Leva quem esta logado sem aceite da politica vigente a tela de aceite.
    "apps.privacy.middleware.ConsentRequiredMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "axes.middleware.AxesMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": os.environ.get("DB_NAME", "defaultdb"),
        "USER": os.environ.get("DB_USER", "avnadmin"),
        "PASSWORD": os.environ.get("DB_PASSWORD", ""),
        "HOST": os.environ.get("DB_HOST", ""),
        "PORT": os.environ.get("DB_PORT", "3306"),
        "OPTIONS": {
            "charset": "utf8mb4",
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
    }
}

DB_SSL_CA = os.environ.get("DB_SSL_CA", "")
if DB_SSL_CA:
    DATABASES["default"]["OPTIONS"]["ssl"] = {"ca": str(BASE_DIR / DB_SSL_CA)}

# Os testes usam um banco temporário em memória, para não criar nem apagar
# nada no servidor do Aiven.
if "test" in sys.argv:
    DATABASES["default"] = {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": ":memory:",
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        "OPTIONS": {"min_length": 10},
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "pt-br"

TIME_ZONE = "America/Sao_Paulo"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_DIRS = [BASE_DIR / "static"]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Os arquivos estáticos são servidos pelo WhiteNoise, que está no MIDDLEWARE
# logo abaixo do SecurityMiddleware. Isso dispensa um servidor de arquivos
# separado, que o plano gratuito do Render não oferece.
#
# O padrão é o armazenamento simples do Django. O manifesto que mapeia cada
# arquivo para o nome com hash só existe depois de rodar collectstatic, e sem
# ele a tag {% static %} levantaria erro em vez de servir a página.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage"},
}

if not DEBUG:
    # Em produção o WhiteNoise comprime os arquivos e grava o hash do conteúdo
    # no nome. Isso permite cache longo no navegador sem risco de servir versão
    # velha: quando o arquivo muda, o nome muda junto. O build.sh roda o
    # collectstatic que gera esse manifesto.
    STORAGES["staticfiles"]["BACKEND"] = (
        "whitenoise.storage.CompressedManifestStaticFilesStorage"
    )

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ---------------------------------------------------------------------------
# Autenticação e senhas (requisitos 1.1 a 1.4)
# ---------------------------------------------------------------------------
AUTH_USER_MODEL = "accounts.User"

PASSWORD_HASHERS = [
    "apps.accounts.hashers.ProjectArgon2PasswordHasher",
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

# A ordem importa: o axes confere primeiro se aquele e-mail e aquele endereço
# estão bloqueados, e nem chega a testar a senha.
AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]


# ---------------------------------------------------------------------------
# Autenticação em duas etapas (requisitos 1.5 e 1.6)
# ---------------------------------------------------------------------------
OTP_TOTP_ISSUER = "Health In Sight"

# Atraso progressivo após códigos inválidos, para dificultar tentativa em massa.
OTP_TOTP_THROTTLE_FACTOR = 1

# Tempo máximo entre a senha correta e a validação do código.
TWO_FACTOR_PENDING_TIMEOUT = timedelta(minutes=5)

# O painel administrativo do django-otp mostra, por padrão, o segredo de cada
# dispositivo e um link para o QR Code. Com isso, qualquer pessoa da equipe
# poderia cadastrar o 2FA de um usuário no próprio celular. Ninguém precisa ver
# esse segredo depois que ele é lido pelo aplicativo autenticador.
OTP_ADMIN_HIDE_SENSITIVE_DATA = True


# ---------------------------------------------------------------------------
# Criptografia de dados em repouso (requisitos 3.4 a 3.6)
# ---------------------------------------------------------------------------

if "test" in sys.argv:
    # Os testes usam uma chave sorteada a cada execução, junto do banco em
    # memória. Nenhuma chave de teste fica escrita no repositório.
    FIELD_ENCRYPTION_KEY = os.urandom(32)
else:
    # A chave vem só do ambiente: do .env na máquina local e das variáveis do
    # painel no Render. O .env está no .gitignore, então a chave nunca chega ao
    # GitHub. São 32 bytes, codificados em base64 para caber em uma variável.
    try:
        FIELD_ENCRYPTION_KEY = base64.urlsafe_b64decode(
            os.environ.get("FIELD_ENCRYPTION_KEY", "")
        )
    except (binascii.Error, ValueError):
        FIELD_ENCRYPTION_KEY = b""

    # Sem chave válida a aplicação não sobe, em desenvolvimento e em produção.
    # A alternativa seria gravar segredos em texto puro ou deixar o 2FA
    # inutilizável, e as duas falhariam em silêncio.
    if len(FIELD_ENCRYPTION_KEY) != 32:
        raise ImproperlyConfigured(
            "FIELD_ENCRYPTION_KEY ausente ou invalida: precisa ter 32 bytes em "
            "base64. Veja o .env.example para gerar uma."
        )


# ---------------------------------------------------------------------------
# Proteção contra força bruta (requisito 1.11)
# ---------------------------------------------------------------------------
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(minutes=5)

# A lista dentro da lista bloqueia a combinação de e-mail e endereço de rede.
# Bloquear só pelo e-mail permitiria travar a conta de qualquer pessoa de
# propósito, bastando errar a senha dela cinco vezes.
AXES_LOCKOUT_PARAMETERS = [["username", "ip_address"]]

AXES_RESET_ON_SUCCESS = True
AXES_LOCKOUT_TEMPLATE = "accounts/lockout.html"


# ---------------------------------------------------------------------------
# Recuperação de senha (requisitos 2.1 a 2.7)
# ---------------------------------------------------------------------------

# Prazo de validade do link enviado por e-mail. Tempo suficiente para a
# mensagem chegar, mesmo com a lentidão do plano gratuito, e curto o bastante
# para limitar a janela em que um link vazado — histórico do navegador, e-mail
# encaminhado, caixa de entrada compartilhada — ainda serviria para alguém.
PASSWORD_RESET_TOKEN_TIMEOUT = timedelta(minutes=30)

# Limite de pedidos de recuperação para o mesmo e-mail dentro da janela. Sem
# isso a tela viraria um disparador aberto de mensagens: qualquer pessoa
# poderia usar o formulário para inundar a caixa de entrada de outra, à custa
# da cota de envio do projeto.
PASSWORD_RESET_MAX_REQUESTS = 3
PASSWORD_RESET_REQUEST_WINDOW = timedelta(minutes=15)

# Envio pela API HTTP do Brevo. A chave fica em variável de ambiente, fora do
# repositório: se estivesse no código, qualquer pessoa com acesso ao histórico
# do Git poderia enviar mensagens em nome do projeto.
BREVO_API_KEY = os.environ.get("BREVO_API_KEY", "")
BREVO_SENDER_EMAIL = os.environ.get("BREVO_SENDER_EMAIL", "")
BREVO_SENDER_NAME = os.environ.get("BREVO_SENDER_NAME", "Health In Sight")

# Endereço público usado para montar o link do e-mail. Vem da configuração e
# não do cabeçalho Host da requisição, que é controlado por quem chama e
# permitiria apontar o link para um site falso. Em produção precisa apontar
# para o endereço https do Render.
APP_BASE_URL = os.environ.get("APP_BASE_URL", "http://localhost:8000")


# ---------------------------------------------------------------------------
# Conformidade com a LGPD (requisitos 4.4 a 4.7)
# ---------------------------------------------------------------------------

# Versão do texto da Política de Privacidade. Cada aceite grava a versão que foi
# aceita. Mudar este valor ao alterar o texto faz com que todas as contas sejam
# levadas a ler e aceitar a versão nova antes de continuar.
PRIVACY_POLICY_VERSION = "1.0"


# ---------------------------------------------------------------------------
# Sessões (requisitos 1.9 e 1.10)
# ---------------------------------------------------------------------------
SESSION_COOKIE_AGE = 900            # 15 minutos
SESSION_SAVE_EVERY_REQUEST = True   # renova a cada requisição (expiração deslizante)
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_HTTPONLY = True      # invisível para JavaScript, mitiga roubo por XSS
SESSION_COOKIE_SAMESITE = "Lax"     # mitiga CSRF


# ---------------------------------------------------------------------------
# Para onde o Django redireciona
# ---------------------------------------------------------------------------
LOGIN_URL = "accounts:login"
LOGIN_REDIRECT_URL = "accounts:profile"
LOGOUT_REDIRECT_URL = "home"


# ---------------------------------------------------------------------------
# Registro de eventos (requisitos 2.6 e 2.7)
# ---------------------------------------------------------------------------
# A trilha de auditoria fica no banco, no modelo PasswordResetLog. Esta
# configuração faz o mesmo evento sair também na saída padrão, que é onde o
# Render coleta os logs do serviço, servindo de segunda cópia fora do banco.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "auditoria": {
            "format": "[{asctime}] {levelname} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "auditoria",
        },
    },
    "loggers": {
        # Vale para todos os aplicativos do projeto, que ficam sob "apps.".
        "apps": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
    },
}


# ---------------------------------------------------------------------------
# Publicação no Render
# ---------------------------------------------------------------------------

# O Render encerra o TLS em um proxy reverso e repassa a requisição em HTTP.
# Sem este cabeçalho o Django entenderia toda requisição como insegura: marcaria
# os cookies como não seguros e entraria em loop de redirecionamento com o
# SECURE_SSL_REDIRECT abaixo. Localmente é inofensivo, porque não há proxy
# nenhum enviando X-Forwarded-Proto.
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

# As proteções abaixo dependem de HTTPS. Ligá-las em desenvolvimento, onde o
# servidor responde em HTTP, tornaria o login impossível: o navegador guardaria
# os cookies como exclusivos de HTTPS e não os devolveria em nenhuma
# requisição.
if not DEBUG:
    SECURE_SSL_REDIRECT = True

    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

    # Um ano. Depois da primeira visita, o navegador passa a recusar HTTP para
    # este domínio por conta própria, sem nem chegar a fazer a requisição.
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"

    # A requisição chega pelo proxy do Render. Sem isto o axes leria o endereço
    # do proxy e bloquearia todos os usuários de uma vez.
    AXES_IPWARE_PROXY_COUNT = 1
