# Generated by Django 5.2.17 on 2026-09-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('SOLICITADO', 'Solicitação recebida'), ('EMAIL_ENVIADO', 'E-mail enviado'), ('EMAIL_FALHOU', 'Falha no envio do e-mail'), ('LIMITE_EXCEDIDO', 'Limite de solicitações excedido'), ('TOKEN_INVALIDO', 'Token inexistente'), ('TOKEN_EXPIRADO', 'Token expirado'), ('TOKEN_JA_USADO', 'Token já utilizado'), ('SENHA_REDEFINIDA', 'Senha redefinida')], max_length=20, verbose_name='evento')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail informado')),
                ('account_exists', models.BooleanField(default=False, verbose_name='conta existente')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereco de rede')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='navegador')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='detalhe')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='registrado em')),
            ],
            options={
                'verbose_name': 'registro de recuperacao de senha',
                'verbose_name_plural': 'registros de recuperacao de senha',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email', 'created_at'], name='audit_passw_email_12638c_idx')],
            },
        ),
    ]
