# Generated by Django 5.2.17 on 2026-09-06 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='passwordresetlog',
            name='audit_passw_email_12638c_idx',
        ),
        migrations.RemoveField(
            model_name='passwordresetlog',
            name='account_exists',
        ),
        migrations.RemoveField(
            model_name='passwordresetlog',
            name='email',
        ),
        migrations.AddField(
            model_name='passwordresetlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='password_reset_logs', to=settings.AUTH_USER_MODEL, verbose_name='usuario'),
        ),
        migrations.AddIndex(
            model_name='passwordresetlog',
            index=models.Index(fields=['user', 'created_at'], name='audit_passw_user_id_cc6ad2_idx'),
        ),
    ]
