# Generated by Django 5.2.17 on 2026-09-20 22:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_remove_passwordresetlog_audit_passw_email_12638c_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('LOGIN_OK', 'Login concluído'), ('LOGIN_FALHOU', 'Senha inválida'), ('LOGOUT', 'Sessão encerrada'), ('OTP_OK', 'Segundo fator validado'), ('OTP_FALHOU', 'Código do segundo fator inválido'), ('OTP_ATIVADO', 'Segundo fator ativado'), ('OTP_DESATIVADO', 'Segundo fator desativado'), ('CONTA_BLOQUEADA', 'Conta bloqueada por tentativas'), ('CADASTRO', 'Conta criada'), ('CONTA_EXCLUIDA', 'Conta excluída pelo titular')], max_length=25, verbose_name='evento')),
                ('usuario_ref', models.IntegerField(blank=True, null=True, verbose_name='identificador selado')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='endereco de rede')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='navegador')),
                ('detail', models.CharField(blank=True, max_length=255, verbose_name='detalhe')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='registrado em')),
                ('hash_anterior', models.CharField(max_length=64, verbose_name='hash do registro anterior')),
                ('hash_atual', models.CharField(max_length=64, unique=True, verbose_name='hash deste registro')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_events', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'evento de autenticacao',
                'verbose_name_plural': 'eventos de autenticacao',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='audit_authe_user_id_67dcb8_idx'), models.Index(fields=['usuario_ref'], name='audit_authe_usuario_7dbfc5_idx')],
            },
        ),
    ]
