# Generated by Django 5.2.17 on 2026-09-22 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='apelido na URL')),
                ('resumo', models.TextField(verbose_name='resumo')),
                ('quando_procurar', models.TextField(verbose_name='quando procurar atendimento')),
            ],
            options={
                'verbose_name': 'condicao',
                'verbose_name_plural': 'condicoes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='titulo')),
                ('resumo', models.TextField(verbose_name='resumo')),
                ('fonte', models.CharField(max_length=120, verbose_name='fonte')),
                ('url_original', models.URLField(verbose_name='endereco original')),
                ('publicado_em', models.DateField(verbose_name='publicado em')),
                ('ativo', models.BooleanField(default=True, verbose_name='ativo')),
            ],
            options={
                'verbose_name': 'material',
                'verbose_name_plural': 'materiais',
                'ordering': ['-publicado_em'],
            },
        ),
        migrations.CreateModel(
            name='Sintoma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60, verbose_name='nome')),
                ('slug', models.SlugField(unique=True, verbose_name='apelido na URL')),
                ('alerta', models.BooleanField(default=False, verbose_name='sinal de alerta')),
            ],
            options={
                'verbose_name': 'sintoma',
                'verbose_name_plural': 'sintomas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Associacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes', to='catalog.condicao', verbose_name='condicao')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes', to='catalog.material', verbose_name='material')),
                ('sintoma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associacoes', to='catalog.sintoma', verbose_name='sintoma')),
            ],
            options={
                'verbose_name': 'associacao',
                'verbose_name_plural': 'associacoes',
                'unique_together': {('sintoma', 'condicao', 'material')},
            },
        ),
    ]
