# Generated by Django 5.2.17 on 2026-09-22 22:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_sintomas_do_escopo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialSalvo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salvo_em', models.DateTimeField(default=django.utils.timezone.now, verbose_name='salvo em')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salvos', to='catalog.material', verbose_name='material')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materiais_salvos', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'material salvo',
                'verbose_name_plural': 'materiais salvos',
                'ordering': ['-salvo_em'],
                'unique_together': {('user', 'material')},
            },
        ),
    ]
