# Generated by Django 5.2.17 on 2026-09-22 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_materialsalvo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='publicado_em',
            field=models.DateField(blank=True, null=True, verbose_name='publicado em'),
        ),
    ]
